name: Deploy Django Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # You can change this to your Python version

    # Install dependencies (you should have a requirements.txt)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run migrations (if needed)
    - name: Run migrations
      run: |
        python manage.py migrate

    # Collect static files (if needed)
    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput

    # Deploy or test your application (this part can vary depending on your setup)
    - name: Deploy (or other tasks)
      run: |
        python manage.py runserver  # Replace with your deployment steps
